name = "tileserver"
usage_model = 'unbound'
main = "dist/worker.es.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2023-12-18"
account_id = "514081276e13c9aa2894e2efde2dc41f"
workers_dev = true

[vars]
API_BASE_URL="https://api.allmaps.org"
TILE_SERVER_BASE_URL="https://allmaps.xyz"
TILE_VIEWER_BASE_URL="https://tiles.allmaps.org"

[build]
command="npm run build"
watch_dir="./src"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
